//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class articulo
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string fabricante { get; set; }
        public string modelo { get; set; }
        public string categoria { get; set; }
        public string codigo_umedida { get; set; }
        public double utilidad { get; set; }
        public string moneda { get; set; }
        public string observacion { get; set; }
    }
    
}
