//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class articulo_detalle
    {
        public long id { get; set; }
        public long codigo_articulo { get; set; }
        public double costo { get; set; }
        public double existencia { get; set; }
        public string almacen { get; set; }
        public string ubicacion { get; set; }
        public string serie_articulo { get; set; }
    }
    
}
