//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class codigospostales
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string asentamiento { get; set; }
        public string tipo_asentamiento { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string ciudad { get; set; }
        public string zona { get; set; }
    }
    
}
