//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class proveedores
    {
        public long codigo { get; set; }
        public string nombre { get; set; }
        public string domicilio_calle { get; set; }
        public string domicilio_colonia { get; set; }
        public string domicilio_poblacion { get; set; }
        public string domicilio_cp { get; set; }
        public string domicilio_estado { get; set; }
        public string domicilio_pais { get; set; }
        public string contacto_nombre { get; set; }
        public string contacto_telefono { get; set; }
        public string contacto_email { get; set; }
        public string contacto_paginaweb { get; set; }
        public string rfc { get; set; }
        public string curp { get; set; }
        public string tipo { get; set; }
        public string observacion { get; set; }
    }
    
}
