//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Entidades;

namespace DAL
{
    public partial class PicoSYSbdEntities : DbContext
    {
        public PicoSYSbdEntities()
            : base("name=PicoSYSbdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<articulo> articulo { get; set; }
        public DbSet<articulo_detalle> articulo_detalle { get; set; }
        public DbSet<codigospostales> codigospostales { get; set; }
        public DbSet<compras> compras { get; set; }
        public DbSet<compras_detalle> compras_detalle { get; set; }
        public DbSet<impuestos> impuestos { get; set; }
        public DbSet<lineas> lineas { get; set; }
        public DbSet<monedas> monedas { get; set; }
        public DbSet<ordencompra> ordencompra { get; set; }
        public DbSet<ordencompra_detalle> ordencompra_detalle { get; set; }
        public DbSet<ordencompra_estados> ordencompra_estados { get; set; }
        public DbSet<proveedores> proveedores { get; set; }
        public DbSet<tipospedido> tipospedido { get; set; }
        public DbSet<unidades_medida> unidades_medida { get; set; }
    }
}
