//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entidades
{
    public partial class ordencompra
    {
        public long folio { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public string codigo_proveedor { get; set; }
        public double impuesto { get; set; }
        public string codigo_almacen { get; set; }
        public string codigo_estado { get; set; }
        public string observacion { get; set; }
        public double tipo_cam { get; set; }
        public string codigo_moneda { get; set; }
        public string ordprov { get; set; }
        public System.DateTime fecha_probableentrega { get; set; }
        public string tipo { get; set; }
        public int tipo_pedido { get; set; }
        public Nullable<long> codigo_compra { get; set; }
    }
    
}
